controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
product_index:
    path: /
    controller: App\Controller\ProductController::index

product_show:
    path: /product/{id}
    controller: App\Controller\ProductController::show