controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
product_index:
    path: /
    controller: App\Controller\ProductController::index

product_page:
    path: /product/{productId}
    controller: App\Controller\ProductPageController::show